import image1 from "../../assets/meals/image1.png";
import image2 from "../../assets/meals/image2.png";
import image3 from "../../assets/meals/image3.png";
import image4 from "../../assets/meals/image4.png";
import image5 from "../../assets/meals/image5.png";
import image6 from "../../assets/meals/image6.png";
import image7 from "../../assets/meals/image7.png";
import image8 from "../../assets/meals/image8.png";
import image9 from "../../assets/meals/image9.png";
import image10 from "../../assets/meals/image10.png";
import image11 from "../../assets/meals/image11.png";
import image12 from "../../assets/meals/image12.png";
import image13 from "../../assets/meals/image13.png";
import image14 from "../../assets/meals/image14.png";
import image15 from "../../assets/meals/image15.png";

const data = [
  {
    image: image1,
    title: "Italian Spaghetti Bolognese",
    foodType: "Keto",
    country: "Italian Cuisine",
    recommended: true,
    popular: true,
    classic: true,
    flexitaria: false,
    id: 1,
    isActive: false,
  },
  {
    image: image2,
    title: "Italian Bruschetta",
    foodType: "Keto",
    country: "Italian Cuisine",
    recommended: true,
    popular: false,
    classic: false,
    flexitaria: true,
    id: 2,
    isActive: false,
    discription: {
      nutritionalValues: [
        { key: "Calori", value: "206.8kcal" },
        { key: "Total Fat", value: "4.0g" },
        { key: "Protein", value: "7.2g" },
        { key: "Total Carbohydrates", value: "35.3g" },
        { key: "Sugar", value: "0.2g" },
        { key: "Dietary fiber", value: "2.3g" },
        { key: "Sodium", value: "428.5mg" },
        { key: "Potassium", value: "106.6mg" },
        { key: "Cholesterol", value: "4.4mg" },
      ],
      ingredients: [
        { key: "6", value: "Roma Tomatoes" },
        { key: "1/3", value: "Cup basil Leaves" },
        { key: "1 tsp", value: "Garlic Cloves" },
        { key: "2 tsp", value: "Balsamic vinegar" },
        { key: "1/2 tsp", value: "Sea salt" },
        { key: "1/4 tsp", value: "Black pepper" },
      ],
      forTheToast: [
        { key: "1", value: "Baguette" },
        { key: "3 tsp", value: "Extra virgin olive oil" },
        { key: "1/3-1/2", value: "Cup shredded parmesan cheese" },
      ],
      link: "https://youtu.be/Q3xg35pcLyo?si=WSUMZcSjzC89Vlbb",
    },
  },
  {
    image: image3,
    title: "Italian Lasagna",
    foodType: "Vegan",
    country: "Italian Cuisine",
    recommended: true,
    popular: true,
    classic: false,
    flexitaria: true,
    id: 3,
    isActive: false,
  },
  {
    image: image4,
    title: "Terriyaki Chicken",
    foodType: "Non-vegan",
    country: "Japanese Cuisine",
    recommended: true,
    popular: false,
    classic: true,
    flexitaria: false,
    id: 4,
    isActive: false,
  },
  {
    image: image5,
    title: "Risotto Alla Milanese",
    foodType: "Keto",
    country: "Italian Cuisine",
    recommended: true,
    popular: false,
    classic: true,
    flexitaria: true,
    id: 5,
    isActive: false,
  },
  {
    image: image6,
    title: "Remen Noodle soup",
    foodType: "Keto",
    country: "Japanese Cuisine",
    recommended: true,
    popular: false,
    classic: false,
    flexitaria: false,
    id: 6,
    isActive: false,
  },
  {
    image: image7,
    title: "Gyudon (Japanese Beef Rice Bowl)",
    foodType: "Non-vegan",
    country: "Japanese Cuisine",
    recommended: true,
    popular: true,
    classic: true,
    flexitaria: true,
    id: 7,
    isActive: false,
  },
  {
    image: image8,
    title: "Salmon Sashimi",
    foodType: "Non-vegan",
    country: "Japanese Cuisine",
    suggest: "Recomended",
    recommended: true,
    popular: false,
    classic: false,
    flexitaria: true,
    id: 8,
    isActive: false,
  },
  {
    image: image9,
    title: "Udon Stir fry",
    foodType: "Keto",
    country: "Japanese Cuisine",
    recommended: true,
    popular: true,
    classic: true,
    flexitaria: false,
    id: 9,
    isActive: false,
  },
  {
    image: image10,
    title: "Butter Chicken",
    foodType: "Keto",
    country: "Indian Cuisine",
    recommended: true,
    popular: false,
    classic: false,
    flexitaria: true,
    id: 10,
    isActive: false,
  },
  {
    image: image11,
    title: "Palak Paneer",
    foodType: "Keto",
    country: "Indian Cuisine",
    recommended: true,
    popular: true,
    classic: false,
    flexitaria: false,
    id: 11,
    isActive: false,
  },
  {
    image: image12,
    title: "Vegetable Korma",
    foodType: "Non-vegan",
    country: "Indian Cuisine",
    recommended: true,
    popular: true,
    classic: false,
    flexitaria: true,
    id: 12,
    isActive: false,
  },
  {
    image: image13,
    title: "Samosas",
    foodType: "Non-vegan",
    country: "Indian Cuisine",
    recommended: true,
    popular: false,
    classic: false,
    flexitaria: true,
    id: 13,
    isActive: false,
  },
  {
    image: image14,
    title: "Chicken Tikka Masala",
    foodType: "Keto",
    country: "Indian Cuisine",
    recommended: true,
    popular: true,
    classic: false,
    flexitaria: true,
    id: 14,
    isActive: false,
  },
  {
    image: image15,
    title: "Chicken Parmesan",
    foodType: "Vegan",
    country: "Indian Cuisine",
    recommended: true,
    popular: false,
    classic: false,
    flexitaria: true,
    id: 15,
    isActive: false,
  },
];

export default data;
